[package]
name = "webhook"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-swap.workspace = true
dashmap.workspace = true
hex.workspace = true
hmac.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shared-types.workspace = true
tokio.workspace = true
url = { workspace = true }

[lints]
workspace = true
