//! 9 家交易所适配器具体实现。
//!
//! 每家适配器都实现 [`ExchangeAdapter`] trait（由 [`crate::adapter`] 提供）。
//!
//! [`ExchangeAdapter`]: crate::adapter::ExchangeAdapter

pub mod binance;
mod binance_config;
mod binance_deposits;
mod binance_exchange_info;
#[allow(dead_code)]
mod binance_fee_evidence;
mod binance_format;
mod binance_funding_info;
mod binance_market_data;
mod binance_metadata;
mod binance_private_data;
mod binance_private_rest;
mod binance_public_rest;
mod binance_response;
mod binance_spot_ws_snapshot;
pub mod binance_spot_ws_user;
mod binance_time;
mod binance_trade_data;
mod binance_transfer_destinations;
mod binance_transfer_networks;
mod binance_user_stream;
mod binance_withdrawals;
mod binance_ws_mark;
mod binance_ws_market;
mod binance_ws_spot_depth;
mod binance_ws_spot_ticker;
mod binance_ws_ticker;
mod binance_ws_trade;
pub mod binance_ws_user;
mod binance_ws_user_data;
pub mod bitget;
mod bitget_config;
mod bitget_deposits;
mod bitget_instruments;
mod bitget_market_data;
mod bitget_order_compiler;
mod bitget_response;
mod bitget_transfer_networks;
mod bitget_uta_config;
mod bitget_uta_market_data;
mod bitget_uta_private_data;
mod bitget_uta_private_rest;
mod bitget_uta_public_rest;
mod bitget_uta_trade_data;
mod bitget_uta_ws_market;
mod bitget_uta_ws_spot_ticker;
mod bitget_uta_ws_ticker;
mod bitget_uta_ws_ticker_data;
mod bitget_uta_ws_trade;
pub mod bitget_uta_ws_user;
mod bitget_uta_ws_user_data;
mod bitget_withdrawals;
pub mod bybit;
mod bybit_config;
mod bybit_credential_data;
mod bybit_deposits;
mod bybit_instruments;
mod bybit_market_data;
mod bybit_private_data;
mod bybit_private_rest;
mod bybit_public_rest;
mod bybit_response;
mod bybit_trade_data;
mod bybit_transfer_networks;
mod bybit_withdrawals;
mod bybit_ws_market;
mod bybit_ws_spot_ticker;
mod bybit_ws_ticker;
mod bybit_ws_ticker_data;
mod bybit_ws_trade;
pub mod bybit_ws_user;
mod bybit_ws_user_data;
mod contract_orderbook;
mod funding_payments;
pub mod gate;
mod gate_config;
mod gate_contracts;
pub mod gate_crossex;
mod gate_crossex_book;
mod gate_crossex_config;
mod gate_crossex_data;
mod gate_crossex_private_data;
mod gate_crossex_rest;
mod gate_crossex_symbols;
mod gate_crossex_ws;
mod gate_crossex_ws_private;
mod gate_fee_evidence;
mod gate_fill_evidence;
mod gate_market_data;
mod gate_private_data;
mod gate_private_rest;
mod gate_public_rest;
mod gate_response;
mod gate_spot_trade_data;
mod gate_spot_ws_trade;
pub mod gate_spot_ws_user;
mod gate_trade_data;
mod gate_transfer_networks;
mod gate_ws_market;
mod gate_ws_spot_ticker;
mod gate_ws_ticker;
mod gate_ws_ticker_data;
mod gate_ws_ticker_runtime;
mod gate_ws_ticker_sbe;
mod gate_ws_trade;
pub mod gate_ws_user;
mod gate_ws_user_data;
pub mod hyperliquid;
mod hyperliquid_config;
mod hyperliquid_instruments;
mod hyperliquid_market_data;
mod hyperliquid_private_data;
mod hyperliquid_public_rest;
mod hyperliquid_trade_data;
mod hyperliquid_ws_active_ctx;
mod hyperliquid_ws_all_mids;
mod hyperliquid_ws_market;
mod hyperliquid_ws_trade;
pub use hyperliquid_ws_trade::{hyperliquid_signer_session_health, HyperliquidSignerSessionHealth};
pub mod hyperliquid_ws_user;
mod hyperliquid_ws_user_data;
mod hyperliquid_ws_user_raw;
pub mod kraken;
mod kraken_config;
mod kraken_futures_book;
mod kraken_futures_data;
mod kraken_futures_private_data;
mod kraken_futures_rest;
mod kraken_futures_ws;
mod kraken_futures_ws_private;
mod kraken_live;
mod kraken_spot_book;
mod kraken_spot_data;
mod kraken_spot_private_data;
mod kraken_spot_rest;
mod kraken_stock_account;
mod kraken_stock_history;
mod kraken_stock_receipts;
mod kraken_stock_funding;
mod kraken_spot_ws;
mod kraken_spot_ws_private;
mod kraken_symbols;
mod kraken_transfer_networks;
mod kraken_funding_rest;
mod kraken_deposits;
mod kraken_withdrawals;
pub mod kucoin;
mod kucoin_config;
mod kucoin_contracts;
mod kucoin_instruments;
mod kucoin_market_data;
mod kucoin_private_data;
mod kucoin_private_rest;
mod kucoin_public_rest;
mod kucoin_response;
mod kucoin_spot_trade_data;
mod kucoin_spot_ws_trade;
pub mod kucoin_spot_ws_user;
mod kucoin_trade_data;
mod kucoin_transfer_networks;
mod kucoin_ws_mark_index;
mod kucoin_ws_mark_index_data;
mod kucoin_ws_market;
mod kucoin_ws_session;
mod kucoin_ws_spot_depth;
mod kucoin_ws_spot_ticker;
mod kucoin_ws_spot_ticker_data;
mod kucoin_ws_ticker;
mod kucoin_ws_ticker_data;
pub mod kucoin_ws_user;
mod kucoin_ws_user_data;
pub mod okx;
mod okx_config;
mod okx_funding;
mod okx_instruments;
pub mod okx_live;
mod okx_live_config;
mod okx_live_data;
mod okx_mark_index_data;
mod okx_market_data;
mod okx_private_data;
mod okx_private_rest;
mod okx_public_rest;
mod okx_read_parse;
mod okx_response;
mod okx_trade_data;
mod okx_transfer_networks;
mod okx_ws_funding;
mod okx_ws_instruments;
mod okx_ws_mark_index;
mod okx_ws_market;
mod okx_ws_spot_depth;
mod okx_ws_spot_ticker;
mod okx_ws_ticker;
mod okx_ws_trade;
pub mod okx_ws_user;
mod okx_ws_user_data;

#[cfg(test)]
mod private_read_order_semantics_tests;
pub(crate) mod spot_instruments;
pub(crate) mod spot_order_contract;
#[cfg(test)]
mod spot_private_product_tests;

pub use binance::{Binance, BinanceConfig, BinanceCredentials};
pub use bitget::{Bitget, BitgetConfig, BitgetCredentials, BitgetMarginMode};
pub use bybit::{Bybit, BybitAccountType, BybitConfig, BybitCredentials};
pub use gate::{Gate, GateConfig, GateCredentials};
pub use gate_crossex::{GateCrossEx, GateCrossExConfig, GateCrossExCredentials};
pub use hyperliquid::{
    Hyperliquid, HyperliquidAccountAbstraction, HyperliquidConfig, HyperliquidCredentialRelation,
    HyperliquidCredentials, HyperliquidMarket,
};
pub use kraken::{
    Kraken, KrakenConfig, KrakenCredentials, KrakenFuturesCredentials, KrakenSpotCredentials,
};
pub use kucoin::{Kucoin, KucoinConfig, KucoinCredentials, KucoinMarginMode};
pub use okx::{Okx, OkxConfig, OkxCredentials};
pub use okx_live::{OkxLive, OkxLiveConfig, OkxLiveCredentials, OkxTdMode};
