#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

read -r -p "Binance Futures Testnet API key: " BINANCE_FUTURES_TESTNET_API_KEY
read -r -s -p "Binance Futures Testnet API secret: " BINANCE_FUTURES_TESTNET_API_SECRET
printf '\n'
read -r -p "Symbol [BTC]: " BINANCE_FUTURES_TESTNET_SYMBOL
read -r -p "Quantity [0.006]: " BINANCE_FUTURES_TESTNET_QUANTITY
read -r -p "Limit price [10000]: " BINANCE_FUTURES_TESTNET_LIMIT_PRICE

BINANCE_FUTURES_TESTNET_SYMBOL="${BINANCE_FUTURES_TESTNET_SYMBOL:-BTC}"
BINANCE_FUTURES_TESTNET_QUANTITY="${BINANCE_FUTURES_TESTNET_QUANTITY:-0.006}"
BINANCE_FUTURES_TESTNET_LIMIT_PRICE="${BINANCE_FUTURES_TESTNET_LIMIT_PRICE:-10000}"

if [[ -z "$BINANCE_FUTURES_TESTNET_API_KEY" || -z "$BINANCE_FUTURES_TESTNET_API_SECRET" ]]; then
  echo "missing api key or secret" >&2
  exit 1
fi

export CRYPTO_ARB_RUN_BINANCE_TESTNET_SMOKE=I_UNDERSTAND_THIS_PLACES_TESTNET_ORDERS
export BINANCE_FUTURES_TESTNET_API_KEY
export BINANCE_FUTURES_TESTNET_API_SECRET
export BINANCE_FUTURES_TESTNET_SYMBOL
export BINANCE_FUTURES_TESTNET_QUANTITY
export BINANCE_FUTURES_TESTNET_LIMIT_PRICE

(
  cd "$PROJECT_ROOT"
  cargo test -p exchange --test binance_testnet_smoke -- --ignored --nocapture
)

unset CRYPTO_ARB_RUN_BINANCE_TESTNET_SMOKE
unset BINANCE_FUTURES_TESTNET_API_KEY
unset BINANCE_FUTURES_TESTNET_API_SECRET
unset BINANCE_FUTURES_TESTNET_SYMBOL
unset BINANCE_FUTURES_TESTNET_QUANTITY
unset BINANCE_FUTURES_TESTNET_LIMIT_PRICE
