import { test, expect } from "@playwright/test";
import { setup, runtime, receipt, closeReceipt, WEB, NOW } from "./fixtures/automation-workbench";

test("automation workspace preserves its draft and fits desktop and mobile", async ({ page }, info) => {
  const fixture = await setup(page);
  await page.goto(`${WEB}/#automation`);
  await expect(page.getByRole("button", { name: "启动模拟自动化", exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath("automation-desktop.png") });
  await page.locator(".automation-entry-config > summary").click();
  await page.getByLabel("资金 (USD)", { exact: true }).fill("12.75");
  fixture.tick();
  await expect(page.getByLabel("资金 (USD)", { exact: true })).toHaveValue("12.75");
  await page.setViewportSize({ width: 390, height: 900 });
  await page.screenshot({ path: info.outputPath("automation-mobile.png") });
  expect(await page.locator(".automation-page").evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBeTruthy();
  expect(await page.locator(".automation-control-rail").evaluate((el) => el.scrollHeight <= el.clientHeight + 1)).toBeTruthy();
  expect(fixture.errors).toEqual([]);
});

test("automation saves validate all numbers serialize writes and retain rejected drafts", async ({ page }) => {
  const fixture = await setup(page);
  await page.goto(`${WEB}/#automation`);
  await page.locator(".automation-entry-config > summary").click();
  const capital = page.getByLabel("资金 (USD)", { exact: true });
  const save = page.getByRole("button", { name: "保存门槛", exact: true });
  await capital.fill("");
  await save.click();
  await expect(page.locator(".automation-action-notice")).toContainText("资金必须");
  expect(fixture.requests.filter((r) => r.method === "PATCH")).toHaveLength(0);
  await capital.fill("12.75");
  await page.getByLabel("入场冷却 (秒)", { exact: true }).fill("1");
  fixture.holdWrite();
  await save.click();
  await expect(capital).toBeDisabled();
  await expect(page.getByRole("button", { name: "正在更新…", exact: true })).toBeDisabled();
  fixture.tick();
  fixture.failWrite();
  fixture.releaseWrite();
  await expect(page.locator(".automation-action-notice")).toContainText("save rejected");
  await expect(capital).toHaveValue("12.75");
  await expect(save).toBeEnabled();
  fixture.failWrite(false);
  await save.click();
  await expect(page.locator(".automation-action-notice")).toHaveText("自动化配置已保存");
  await expect(page.locator(".automation-entry-config .automation-draft-state")).toContainText("与已保存配置一致");
  await expect(page.locator(".automation-guard-summary")).toContainText("$12.75");
  expect(fixture.requests.filter((r) => r.method === "PATCH").map((r) => r.body.capitalUsd)).toEqual([12.75, 12.75]);
  expect(fixture.requests.filter((r) => r.method === "PATCH").map((r) => r.body.cooldownSecs)).toEqual([1, 1]);
  expect(fixture.errors).toEqual([]);
});

test("automation start pause resume emergency stop and late reads follow backend receipts", async ({ page }) => {
  const fixture = await setup(page);
  await page.goto(`${WEB}/#automation`);
  await page.getByRole("button", { name: "启动模拟自动化", exact: true }).click();
  await expect(page.locator(".automation-board-header h2")).toHaveText("监控候选");
  fixture.holdRead();
  await page.getByRole("button", { name: "刷新运行态", exact: true }).click();
  await expect(page.getByRole("button", { name: "读取中…", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "暂停模拟新入场", exact: true }).click();
  await expect(page.locator(".automation-board-header h2")).toHaveText("已暂停");
  fixture.releaseRead();
  await expect(page.getByRole("button", { name: "刷新运行态", exact: true })).toBeEnabled();
  await expect(page.locator(".automation-board-header h2")).toHaveText("已暂停");
  await page.getByRole("button", { name: "恢复模拟自动提交", exact: true }).click();
  await expect(page.locator(".automation-board-header h2")).toHaveText("监控候选");
  await page.getByRole("button", { name: "立即急停", exact: true }).click();
  await expect(page.locator(".automation-board-header h2")).toHaveText("已关闭");
  await page.reload();
  await expect(page.locator(".automation-board-header h2")).toHaveText("已关闭");
  expect(fixture.requests.filter((r) => r.path === "/api/automation/control").map((r) => r.body.action)).toEqual(["pause", "resume", "emergency_stop"]);
  expect(fixture.errors).toEqual([]);
});

test("automation read failures and silent stale state cannot claim live readiness", async ({ page }) => {
  const fixture = await setup(page);
  await page.goto(`${WEB}/#automation`);
  await expect(page.getByRole("button", { name: "启动模拟自动化", exact: true })).toBeEnabled();
  fixture.failRead();
  await page.getByRole("button", { name: "刷新运行态", exact: true }).click();
  await expect(page.locator(".automation-sync-status")).toContainText("automation unavailable");
  await expect(page.getByRole("button", { name: "等待状态确认", exact: true })).toBeDisabled();
  await expect(page.locator(".automation-board-header h2")).toHaveText("运行态待确认");
  fixture.failRead(false);
  await page.getByRole("button", { name: "刷新运行态", exact: true }).click();
  await expect(page.getByRole("button", { name: "启动模拟自动化", exact: true })).toBeEnabled();
  fixture.holdRead();
  await page.getByRole("button", { name: "刷新运行态", exact: true }).click();
  await page.clock.setFixedTime(NOW + 16_000);
  await expect(page.locator(".automation-sync-status")).toContainText("超过 15 秒");
  await expect(page.getByRole("button", { name: "等待状态确认", exact: true })).toBeDisabled();
  fixture.releaseRead();
  await expect(page.getByRole("button", { name: "启动模拟自动化", exact: true })).toBeEnabled();
  expect(fixture.errors).toEqual([]);
});

test("automation decisions keep distinct runs and expanded details across websocket frames", async ({ page }, info) => {
  const fixture = await setup(page);
  const status = runtime();
  status.config.enabled = true;
  status.state = "watching";
  status.recentDecisions = ["SOL", "ETH"].map((symbol, index) => ({ id: `fixture-${symbol}`, kind: "submitted", symbol,
    reason: "fixture: submitted", executionRunId: `fixture-run-${index}`, occurredAtMs: NOW - index * 1000 }));
  status.lastDecision = status.recentDecisions[0];
  fixture.setStatus(status);
  await page.goto(`${WEB}/#automation`);
  await page.locator(".automation-guard-summary > summary").click();
  fixture.tick();
  await expect(page.locator(".automation-guard-summary")).toHaveAttribute("open", "");
  expect(await page.locator(".automation-metric-strip strong").evaluateAll((elements) => elements.every((el) => el.scrollHeight <= el.clientHeight + 1))).toBeTruthy();
  await page.screenshot({ path: info.outputPath("automation-running.png") });
  await page.getByRole("tab", { name: "当前闭环", exact: true }).click();
  const finality = page.locator(".automation-flow-panel li").nth(4);
  await expect(finality).toHaveAttribute("data-state", "current");
  await expect(finality).toContainText("成交待核对");
  await page.screenshot({ path: info.outputPath("automation-flow.png") });
  await page.getByRole("tab", { name: "决策历史", exact: true }).click();
  const table = page.getByRole("table", { name: "自动化决策历史" });
  await expect(table.locator("tbody tr")).toHaveCount(2);
  const details = table.locator('[data-decision-id="fixture-SOL"] details');
  await details.locator("summary").click();
  await details.locator("summary").focus();
  fixture.tick();
  await expect(details).toHaveAttribute("open", "");
  await expect(details.locator("summary")).toBeFocused();
  await expect(details).toContainText("fixture-run-0");
  await page.screenshot({ path: info.outputPath("automation-history-desktop.png") });
  await page.setViewportSize({ width: 390, height: 900 });
  await table.scrollIntoViewIfNeeded();
  expect(await page.locator(".automation-page").evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBeTruthy();
  expect(await table.evaluate((el) => el.getBoundingClientRect().width <= window.innerWidth)).toBeTruthy();
  await expect(details).toContainText("fixture-run-0");
  await table.screenshot({ path: info.outputPath("automation-history-mobile.png") });
  expect(fixture.errors).toEqual([]);
});

test("automation late write after leaving cannot crash or restart a paused strategy", async ({ page }) => {
  const fixture = await setup(page);
  const status = runtime();
  status.config.enabled = true;
  status.state = "watching";
  fixture.setStatus(status);
  await page.goto(`${WEB}/#automation`);
  await expect(page.locator(".automation-board-header h2")).toHaveText("监控候选");
  fixture.failRead();
  await page.getByRole("button", { name: "刷新运行态", exact: true }).click();
  await expect(page.getByRole("button", { name: "暂停新入场（状态待确认）", exact: true })).toBeEnabled();
  fixture.holdWrite();
  await page.getByRole("button", { name: "暂停新入场（状态待确认）", exact: true }).click();
  await expect(page.getByRole("button", { name: "正在更新…", exact: true })).toBeDisabled();
  await page.goto(`${WEB}/#futures`);
  fixture.failRead(false);
  fixture.releaseWrite();
  await page.goto(`${WEB}/#automation`);
  await expect(page.locator(".automation-board-header h2")).toHaveText("已暂停");
  expect(fixture.requests.filter((r) => r.path === "/api/automation/control")).toHaveLength(1);
  expect(fixture.errors).toEqual([]);
});

test("automation protection keeps fractional thresholds and webhook distinguishes acceptance from delivery", async ({ page }) => {
  const fixture = await setup(page);
  await page.goto(`${WEB}/#automation`);
  await page.locator(".automation-protection > summary").click();
  const amount = page.getByLabel("最低净利润 USD", { exact: true });
  await amount.fill("0.0625");
  fixture.tick();
  await expect(amount).toHaveValue("0.0625");
  fixture.holdWrite();
  await page.getByRole("button", { name: "保存退出保护", exact: true }).click();
  await expect(amount).toBeDisabled();
  fixture.releaseWrite();
  await expect(page.locator(".automation-protection-message")).toHaveText("退出保护已保存");
  await expect(amount).toHaveValue("0.0625");
  const patch = fixture.requests.find((r) => r.path === "/api/trading/risk-config")?.body;
  expect(patch.autoProfitClose.minNetProfitUsd).toBe(0.0625);
  await page.locator(".webhook-monitor-disclosure > summary").click();
  fixture.holdWrite();
  const testButton = page.getByRole("button", { name: "测试投递", exact: true });
  await testButton.click();
  await expect(page.getByRole("button", { name: "提交中", exact: true })).toBeDisabled();
  fixture.releaseWrite();
  await expect(page.locator(".automation-delivery-rail")).toContainText("测试请求已受理");
  expect(fixture.requests.filter((r) => r.path === "/api/webhook/test")).toHaveLength(1);
  expect(fixture.errors).toEqual([]);
});

test("automation receipts follow leg finality and exact linked closes without submitting orders", async ({ page }, info) => {
  const fixture = await setup(page);
  const status = runtime();
  status.config.enabled = true;
  status.state = "submitting";
  status.activeRunCount = 1;
  status.lastDecision = { id: "decision-receipt", kind: "submitted", symbol: "SOL", reason: "fixture: submitted",
    executionRunId: "fixture-run-0", occurredAtMs: NOW };
  status.recentDecisions = [status.lastDecision];
  const evidence = receipt();
  fixture.setReceipt(evidence);
  fixture.setStatus(status);
  await page.goto(`${WEB}/#automation`);
  await page.getByRole("button", { name: "查看回执", exact: true }).click();
  const panel = page.getByRole("region", { name: "自动化运行回执", exact: true });
  await expect(panel).toContainText("ACK，非成交终态");
  await expect(panel).toContainText("尚无匹配的平仓回执");
  const emitRun = () => fixture.execution({ event: "execution_run_updated", executionRun: evidence.run, timestampMs: ++evidence.run.updatedAtMs });
  Object.assign(evidence.run.longLeg, { state: "filled", filledQuantity: 1, filledNotionalUsd: 10,
    finalitySource: "private_ws", confirmedFilledAtMs: NOW });
  emitRun();
  await expect(panel.locator(".automation-receipt-leg").first()).toContainText("已成交");
  await page.getByRole("tab", { name: "当前闭环", exact: true }).click();
  await expect(page.locator(".automation-flow-panel li").nth(4)).toContainText("等待双腿成交证据");
  evidence.run.state = "unwind_required";
  emitRun();
  await expect(page.locator(".automation-flow-panel li").nth(4)).toHaveAttribute("data-state", "blocked");
  Object.assign(evidence.run.shortLeg, { state: "filled", filledQuantity: 1, filledNotionalUsd: 10,
    finalitySource: "private_ws", confirmedFilledAtMs: NOW });
  evidence.run.state = "hedged";
  emitRun();
  await expect(page.locator(".automation-flow-panel li").nth(4)).toHaveAttribute("data-state", "complete");
  const close = closeReceipt(evidence.run);
  const wrongClose = structuredClone(close);
  wrongClose.id = "wrong-ticket";
  wrongClose.legs.forEach((leg) => { leg.pairEvidence.ticketId = "other-ticket"; });
  const emitClose = (value: typeof close) => fixture.execution({ event: "close_run_updated", closeRun: value, timestampMs: ++value.updatedAtMs });
  emitClose(wrongClose);
  emitClose(close);
  await expect(page.locator(".automation-flow-panel li").nth(5)).toHaveAttribute("data-state", "warning");
  await page.getByRole("tab", { name: "运行回执", exact: true }).click();
  await expect(panel.locator(".automation-close-receipt")).toHaveCount(1);
  const details = panel.locator(".automation-close-receipt");
  await details.locator("summary").click();
  await details.locator("summary").focus();
  close.status = "failed";
  emitClose(close);
  await expect(details).toContainText("平仓失败");
  close.status = "succeeded";
  close.message = "fixture: fills confirmed; costs still unknown";
  close.legs.forEach((leg) => Object.assign(leg, { status: "filled", finalitySource: "private_ws", confirmedFilledAtMs: NOW }));
  close.legs[1].quantity = 0.5;
  emitClose(close);
  await page.getByRole("tab", { name: "当前闭环", exact: true }).click();
  await expect(page.locator(".automation-flow-panel li").nth(5)).toHaveAttribute("data-state", "warning");
  await page.getByRole("tab", { name: "运行回执", exact: true }).click();
  await details.locator("summary").click();
  await details.locator("summary").focus();
  close.legs[1].quantity = 1;
  emitClose(close);
  await expect(details).toHaveAttribute("open", "");
  await expect(details.locator("summary")).toBeFocused();
  await expect(details).toContainText("本次平仓已成交");
  await expect(details).toContainText("退出费用尚未核清");
  await page.screenshot({ path: info.outputPath("automation-receipts-desktop.png") });
  await page.setViewportSize({ width: 390, height: 900 });
  await panel.scrollIntoViewIfNeeded();
  expect(await page.locator(".automation-page").evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBeTruthy();
  await panel.screenshot({ path: info.outputPath("automation-receipts-mobile.png") });
  await page.getByRole("tab", { name: "当前闭环", exact: true }).click();
  await expect(page.locator(".automation-flow-panel li").nth(5)).toHaveAttribute("data-state", "complete");
  await expect(page.locator(".automation-flow-panel li").nth(6)).toContainText("净收益待核算");
  expect(fixture.requests.every((request) => request.method === "GET")).toBeTruthy();
  expect(fixture.writes).toEqual([]);
  expect(fixture.errors).toEqual([]);
});

test("automation receipts fence old reads run switches and failed refreshes", async ({ page }) => {
  const fixture = await setup(page);
  const status = runtime();
  status.recentDecisions = ["fixture-run-0", "fixture-run-1"].map((id) => ({ id, kind: "submitted", symbol: "SOL",
    reason: "fixture: submitted", executionRunId: id, occurredAtMs: NOW }));
  status.lastDecision = status.recentDecisions[0];
  const first = receipt();
  const second = receipt("fixture-run-1");
  second.run.netExposureUsd = 7;
  fixture.setReceipt(first);
  fixture.setReceipt(second);
  fixture.setStatus(status);
  await page.goto(`${WEB}/#automation`);
  await page.getByRole("tab", { name: "运行回执", exact: true }).click();
  const panel = page.getByRole("region", { name: "自动化运行回执", exact: true });
  await expect(panel.locator(".automation-receipt-summary")).toContainText("fixture-run-0");
  fixture.holdReceipt("fixture-run-0");
  await panel.getByRole("button", { name: "刷新回执", exact: true }).click();
  await expect(panel.getByRole("button", { name: "读取中…", exact: true })).toBeDisabled();
  first.run.netExposureUsd = 3;
  fixture.execution({ event: "execution_run_updated", executionRun: first.run, timestampMs: NOW + 1 });
  await expect(panel.locator(".automation-receipt-summary > div").nth(2)).toContainText("3");
  fixture.releaseReceipt();
  await expect(panel.getByRole("button", { name: "刷新回执", exact: true })).toBeEnabled();
  await expect(panel.locator(".automation-receipt-summary > div").nth(2)).toContainText("3");
  fixture.holdReceipt("fixture-run-0");
  await panel.getByRole("button", { name: "刷新回执", exact: true }).click();
  await expect(panel.getByRole("button", { name: "读取中…", exact: true })).toBeDisabled();
  await page.getByLabel("选择自动化运行记录").selectOption("fixture-run-1");
  await expect(panel.locator(".automation-receipt-summary")).toContainText("fixture-run-1");
  fixture.releaseReceipt();
  await expect(panel.locator(".automation-receipt-summary > div").nth(2)).toContainText("7");
  fixture.failReceipt();
  await panel.getByRole("button", { name: "刷新回执", exact: true }).click();
  await expect(panel.getByRole("status")).toContainText("回执待确认，保留上次记录");
  await expect(panel.locator(".automation-receipt-summary")).toContainText("fixture-run-1");
  fixture.failReceipt(false);
  await panel.getByRole("button", { name: "刷新回执", exact: true }).click();
  await expect(panel.getByRole("status")).toContainText("本地执行账本");
  fixture.holdReceipt("fixture-run-1");
  await panel.getByRole("button", { name: "刷新回执", exact: true }).click();
  await expect(panel.getByRole("button", { name: "读取中…", exact: true })).toBeDisabled();
  await page.goto(`${WEB}/#futures`);
  fixture.releaseReceipt();
  expect(fixture.errors).toEqual([]);
});
