import { expect, test, type Page } from "@playwright/test";
import { API, WEB, NOW, setup, runtime, receipt } from "./fixtures/automation-workbench";

const navigate = (page: Page, id: string) => page.locator(`.module-tabs button[data-module="${id}"]`).click();

test("automation hung reads expire, preserve drafts and cancel when leaving without writes", async ({ page }, info) => {
  await page.clock.install({ time: NOW });
  const f = await setup(page);
  const failed: string[] = [];
  page.on("requestfailed", request => failed.push(new URL(request.url()).pathname));
  f.holdRead();
  let webhookReads = 0, holdWebhook = true, releaseWebhook = () => {};
  await page.route(API + "/api/webhook/status", async route => {
    webhookReads++;
    if (holdWebhook) await new Promise<void>(resolve => { releaseWebhook = resolve; });
    await route.fulfill({ json: f.webhook }).catch(() => {});
  });
  await page.goto(WEB + "/#automation");
  const refresh = page.locator(".automation-main-column > .automation-sync-status button");
  await expect(refresh).toBeDisabled();
  await page.clock.runFor(14_000);
  expect(f.requests.filter(r => r.path === "/api/automation/status")).toHaveLength(1);
  expect(webhookReads).toBe(1);
  await page.clock.runFor(1_100);
  await expect(refresh).toBeEnabled();
  await expect(page.locator(".automation-main-column > .automation-sync-status")).toContainText("15 秒");
  await expect.poll(() => failed.includes("/api/automation/status")).toBe(true);
  await expect.poll(() => failed.includes("/api/webhook/status")).toBe(true);
  holdWebhook = false; releaseWebhook(); f.releaseRead();
  await refresh.click();
  await expect(page.locator(".automation-command-status strong")).toHaveText("已关闭");
  const rules = page.locator(".automation-entry-config");
  if (await rules.getAttribute("open") === null) await rules.locator("summary").click();
  await page.getByLabel("资金 (USD)", { exact: true }).fill("12.75");
  f.holdRead(); await refresh.click();
  await expect(refresh).toBeDisabled();
  const failedBefore = failed.filter(path => path === "/api/automation/status").length;
  await navigate(page, "futures");
  await expect.poll(() => failed.filter(path => path === "/api/automation/status").length).toBeGreaterThan(failedBefore);
  f.releaseRead();
  await navigate(page, "automation");
  if (await rules.getAttribute("open") === null) await rules.locator("summary").click();
  await expect(refresh).toBeEnabled();
  await expect(page.getByLabel("资金 (USD)", { exact: true })).toHaveValue("12.75");
  await page.clock.runFor(5_100);
  await expect(page.locator(".automation-delivery-rail")).not.toContainText("15 秒");
  await page.screenshot({ path: info.outputPath("automation-read-recovered-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await refresh.scrollIntoViewIfNeeded();
  await refresh.click({ trial: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath("automation-read-recovered-mobile.png") });
  expect(f.requests.every(r => r.method === "GET")).toBe(true);
  expect(f.writes).toEqual([]); expect(f.errors).toEqual([]);
});

test("automation receipt timeout and record switches cancel old reads and retain newer fills", async ({ page }, info) => {
  await page.clock.install({ time: NOW });
  const f = await setup(page), status = runtime();
  status.recentDecisions = ["fixture-run-0", "fixture-run-1"].map(id => ({ id, kind: "submitted", symbol: "SOL",
    reason: "fixture: submitted", executionRunId: id, occurredAtMs: NOW }));
  status.lastDecision = status.recentDecisions[0];
  const first = receipt(), second = receipt("fixture-run-1");
  second.run.netExposureUsd = 7;
  f.setReceipt(first); f.setReceipt(second); f.setStatus(status);
  const failed: string[] = [];
  page.on("requestfailed", request => failed.push(new URL(request.url()).pathname));
  await page.goto(WEB + "/#automation");
  await page.getByRole("tab", { name: "交易记录", exact: true }).click();
  const panel = page.getByRole("region", { name: "自动化交易记录", exact: true });
  const refresh = panel.getByRole("button", { name: "刷新处理结果", exact: true });
  await expect(panel).toContainText("fixture-run-0");
  f.holdReceipt("fixture-run-0"); await refresh.click();
  await page.clock.runFor(15_100);
  await expect(refresh).toBeEnabled();
  await expect(panel.getByRole("status")).toContainText("15 秒");
  await expect(panel.locator(".automation-receipt-summary")).toContainText("fixture-run-0");
  await expect.poll(() => failed.includes("/api/automation/execution-runs/fixture-run-0")).toBe(true);
  f.releaseReceipt(); await refresh.click();
  await expect(panel.getByRole("status")).toContainText("本地执行账本");
  f.holdReceipt("fixture-run-0"); await refresh.click();
  const cancelled = failed.length;
  await page.getByLabel("选择自动化运行记录").selectOption("fixture-run-1");
  await expect.poll(() => failed.length).toBeGreaterThan(cancelled);
  await expect(panel.locator(".automation-receipt-summary")).toContainText("fixture-run-1");
  f.releaseReceipt();
  f.holdReceipt("fixture-run-1"); await refresh.click();
  second.run.netExposureUsd = 3; second.run.updatedAtMs++;
  f.execution({ event: "execution_run_updated", executionRun: second.run, timestampMs: NOW + 20_000 });
  await expect(panel.locator(".automation-receipt-summary > div").nth(2)).toContainText("3");
  f.releaseReceipt();
  await expect(refresh).toBeEnabled();
  await expect(panel.locator(".automation-receipt-summary > div").nth(2)).toContainText("3");
  await panel.screenshot({ path: info.outputPath("automation-receipt-recovered.png") });
  f.holdReceipt("fixture-run-1"); await refresh.click();
  const leaving = failed.length;
  await navigate(page, "futures");
  await expect.poll(() => failed.length).toBeGreaterThan(leaving);
  f.releaseReceipt();
  expect(f.requests.every(r => r.method === "GET")).toBe(true);
  expect(f.writes).toEqual([]); expect(f.errors).toEqual([]);
});
