import { expect, test } from "@playwright/test";
import { executionFixture, openExecution } from "./fixtures/execution-workbench";
import { NOW } from "./fixtures/opportunity-workbench";

test("execution checks time out without submitting and recover with the same inputs", async ({ page }) => {
  await page.clock.install({ time: NOW });
  const f = await executionFixture(page);
  f.holdPreview();
  await page.goto("/#futures");
  await page.getByRole("button", { name: "创建交易计划", exact: true }).click();
  await expect.poll(() => f.previews.length).toBe(1);
  const refresh = page.getByRole("button", { name: "刷新预览", exact: true });
  const submit = page.locator(".confirm-action.primary");
  const artifact = page.locator(".execution-artifact");
  const capital = page.getByRole("textbox", { name: "计划本金 USD", exact: true });
  const originalCapital = await capital.inputValue();
  await page.clock.runFor(15_100);
  await expect(page.locator(".execution-actionbar")).toContainText("15 秒");
  await expect(submit).toBeDisabled();
  await expect(capital).toHaveValue(originalCapital);
  expect(f.previews).toHaveLength(1);
  const oldPreview = page.waitForResponse("**/fixture-perp_cross-BTC/preview");
  f.releasePreview();
  await (await oldPreview).finished();
  await expect(page.locator(".execution-actionbar")).toContainText("15 秒");

  f.setServerTime(NOW + 15_100);
  f.holdBuild();
  await refresh.click();
  await expect.poll(() => f.builds.length).toBe(1);
  await page.clock.runFor(15_100);
  await expect(artifact).toContainText("15 秒");
  await expect(submit).toBeDisabled();
  const oldBuild = page.waitForResponse("**/execution-artifacts/build");
  f.releaseBuild();
  await (await oldBuild).finished();
  await expect(artifact).toContainText("15 秒");
  const rebuild = artifact.getByRole("button", { name: "重新生成", exact: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await rebuild.click({ trial: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath("execution-check-timeout-mobile.png") });
  await rebuild.click();
  await page.setViewportSize({ width: 1440, height: 900 });
  await expect(artifact.locator(".execution-artifact-status")).toContainText("待校验");
  expect(f.previews).toHaveLength(2);
  expect(f.builds).toHaveLength(2);
  expect(f.builds[1]).toEqual(f.builds[0]);

  f.setServerTime(NOW + 30_200);
  await refresh.click();
  await expect.poll(() => f.builds.length).toBe(3);
  f.holdValidation();
  await artifact.getByRole("button", { name: "检查交易计划", exact: true }).click();
  await expect.poll(() => f.validations.length).toBe(1);
  await page.clock.runFor(15_100);
  await expect(artifact).toContainText("15 秒");
  await expect(artifact.getByRole("checkbox")).toBeDisabled();
  await expect(submit).toBeDisabled();
  const oldValidation = page.waitForResponse("**/execution-artifacts/validate");
  f.releaseValidation();
  await (await oldValidation).finished();
  await expect(artifact.locator(".execution-artifact-status")).toContainText("校验失败");
  await artifact.getByRole("button", { name: "检查交易计划", exact: true }).click();
  await artifact.getByRole("checkbox").check();
  await expect(submit).toBeEnabled();
  await expect(capital).toHaveValue(originalCapital);
  await artifact.scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath("execution-check-recovered-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await submit.click({ trial: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath("execution-check-recovered-mobile.png") });
  expect(f.validations[1]).toEqual(f.validations[0]);
  expect(f.errors).toEqual([]);
  expect(f.writes).toEqual([]);
});

test("reminder checks recover after timeout without importing an old reply or placing orders", async ({ page }) => {
  await page.clock.install({ time: NOW });
  const f = await executionFixture(page);
  await openExecution(page);
  const code = f.handoffCode();
  await page.goto("/#execution");
  await page.reload();
  const inbox = page.locator(".execution-artifact-inbox");
  await inbox.locator("summary").click();
  const input = inbox.getByLabel("Webhook 校验码");
  const verify = inbox.getByRole("button", { name: "检查通知中的计划", exact: true });
  await input.fill(code);
  f.holdValidation();
  await verify.click();
  await expect.poll(() => f.validations.length).toBe(1);
  await page.clock.runFor(15_100);
  await expect(inbox).toContainText("15 秒");
  await expect(verify).toBeEnabled();
  await expect(input).toHaveValue(code);
  const old = page.waitForResponse("**/execution-artifacts/validate");
  f.releaseValidation();
  await (await old).finished();
  await expect(inbox).toContainText("15 秒");
  await verify.click();
  await expect(inbox).toContainText("通知中的计划检查通过 · 未下单");
  await expect(inbox.getByRole("link", { name: "查看当前机会", exact: true })).toBeVisible();
  await expect(page.locator(".confirm-action.primary")).toHaveCount(0);
  expect(f.previews).toHaveLength(1);
  expect(f.builds).toHaveLength(1);
  expect(f.validations).toHaveLength(2);
  expect(f.errors).toEqual([]);
  expect(f.writes).toEqual([]);
});
