import { expect, test, type Page } from "@playwright/test";
import { settingsEvidenceFixture } from "./fixtures/settings-evidence";
import { settingsFixture } from "./fixtures/settings-workbench";
import { API, NOW } from "./fixtures/opportunity-workbench";

function cancellations(page: Page) {
  const paths: string[] = [];
  page.on("requestfailed", request => paths.push(new URL(request.url()).pathname));
  return paths;
}

test("settings history reads time out, keep the selected record and retry without writes", async ({ page }, info) => {
  const f = await settingsEvidenceFixture(page, "action-runs");
  const aborted = cancellations(page);
  await page.clock.install({ time: NOW });
  await page.goto("/#settings");
  const row = page.locator('[data-action-id="fixture-action-0"]');
  await row.getByRole("button").click();
  const detail = page.getByRole("region", { name: "动作详情", exact: true });
  await expect(detail).toContainText("fixture receipt 0");
  const paths = ["/api/trading/action-runs", "/api/trading/action-runs/fixture-action-0"];
  for (const path of paths) f.holdEvidence(`GET ${path}`);
  await page.getByRole("button", { name: "刷新", exact: true }).click();
  await expect.poll(() => f.calls.filter(r => r.key === `GET ${paths[1]}`).length).toBe(2);
  await page.clock.runFor(15_100);
  await expect(page.locator(".settings-workspace")).toContainText("15 秒");
  await expect(detail).toContainText("fixture receipt 0");
  await expect(page.locator('[data-module="settings"]')).toHaveAttribute("data-runtime-state", "stale");
  for (const path of paths) {
    await expect.poll(() => aborted.includes(path)).toBe(true);
    f.releaseEvidence(`GET ${path}`);
  }
  await page.getByRole("button", { name: "刷新", exact: true }).click();
  await expect(page.locator('[data-module="settings"]')).toHaveAttribute("data-runtime-state", "ready");
  await expect(page.locator(".settings-workspace")).not.toContainText("15 秒");
  await page.screenshot({ path: info.outputPath("settings-records-recovered.png") });
  expect(f.calls.every(r => r.key.startsWith("GET "))).toBe(true);
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});

test("webhook reads release the refresh button and retain drafts across push, timeout and navigation", async ({ page }, info) => {
  const f = await settingsFixture(page);
  const aborted = cancellations(page);
  await page.clock.install({ time: NOW });
  await page.goto("/#settings");
  const refresh = page.getByRole("button", { name: "刷新通知状态", exact: true });
  await expect(refresh).toBeEnabled();
  await expect.poll(() => f.channelSockets.get("webhook")?.size ?? 0).toBeGreaterThan(0);
  await page.locator(".webhook-advanced-settings summary").click();
  await page.getByLabel("单次等待上限 (ms)").fill("22000");
  const path = "/api/webhook/status", key = `GET ${path}`;
  f.hold(key);
  await refresh.click();
  await expect(refresh).toBeDisabled();
  f.webhook.updatedAtMs++; f.webhook.deliveredTotal = 9; f.emit();
  await expect(page.locator(".webhook-summary")).toContainText("成功 9");
  await expect(refresh).toBeEnabled();
  await expect.poll(() => aborted.filter(p => p === path).length).toBe(1);
  f.release(key);
  f.hold(key);
  await refresh.click();
  await page.clock.runFor(15_100);
  await expect(refresh).toBeEnabled();
  await expect(page.locator(".webhook-settings")).toContainText("15 秒");
  await expect(page.getByLabel("单次等待上限 (ms)")).toHaveValue("22000");
  await expect(page.locator(".webhook-summary")).toContainText("成功 9");
  await expect.poll(() => aborted.filter(p => p === path).length).toBe(2);
  f.release(key);
  await refresh.click();
  await expect(page.locator(".webhook-settings")).not.toContainText("15 秒");
  f.hold(key);
  await refresh.click();
  await expect(refresh).toBeDisabled();
  await page.getByRole("tab", { name: "行情", exact: true }).click();
  await expect.poll(() => aborted.filter(p => p === path).length).toBe(3);
  f.release(key);
  const market = "/api/system/market-subscriptions";
  await expect(page.getByRole("checkbox", { name: "kraken 现货", exact: true })).toBeChecked();
  f.hold(`GET ${market}`);
  await page.getByRole("button", { name: "刷新行情订阅" }).click();
  await page.clock.runFor(15_100);
  await expect(page.getByRole("button", { name: "刷新行情订阅" })).toBeEnabled();
  await expect(page.getByRole("alert")).toContainText("15 秒");
  await expect.poll(() => aborted.includes(market)).toBe(true);
  f.release(`GET ${market}`);
  await page.getByRole("button", { name: "刷新行情订阅" }).click();
  await expect(page.getByRole("checkbox", { name: "kraken 现货", exact: true })).toBeEnabled();
  await page.getByRole("tab", { name: "消息通知", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "通知方式", exact: true })).toHaveValue("bark");
  await page.locator(".webhook-advanced-settings summary").click();
  await expect(page.getByLabel("单次等待上限 (ms)")).toHaveValue("22000");
  await page.setViewportSize({ width: 390, height: 844 });
  await refresh.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath("settings-notifications-mobile.png") });
  expect(f.requests.every(r => r.method === "GET")).toBe(true);
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});

test("diagnostic refresh replaces old reads, times out as a group and keeps search and symbol inputs", async ({ page }) => {
  const f = await settingsEvidenceFixture(page, "diagnostics");
  const aborted = cancellations(page);
  await page.clock.install({ time: NOW });
  const paths = ["/api/trading/credentials/env-template", "/api/system/venue-operation-health",
    "/api/system/venue-runtime-health", "/api/system/market-data-diagnostics", "/api/arbitrage/funding-rates"];
  const bodies = new Map<string, any>();
  for (const path of paths) bodies.set(path, await (await page.request.get(API + path)).json());
  let hold = false;
  const waiting: (() => void)[] = [];
  await page.route("**/api/**", async route => {
    const path = new URL(route.request().url()).pathname;
    if (route.request().method() !== "GET" || !bodies.has(path)) return route.fallback();
    if (hold) await new Promise<void>(resolve => waiting.push(resolve));
    await route.fulfill({ json: bodies.get(path) });
  });
  await page.goto("/#settings");
  await page.getByRole("tab", { name: "运行数据依据", exact: true }).click();
  const search = page.getByRole("textbox", { name: "搜索状态" });
  await expect(page.locator(".env-template-box textarea")).toBeVisible();
  await search.fill("binance");
  hold = true;
  const refresh = page.getByRole("button", { name: "刷新全部诊断", exact: true });
  await refresh.click();
  await expect.poll(() => waiting.length).toBe(5);
  await refresh.click();
  await expect.poll(() => waiting.length).toBe(10);
  for (const path of paths) await expect.poll(() => aborted.filter(p => p === path).length).toBe(1);
  await page.getByRole("tab", { name: "行情", exact: true }).last().click();
  const symbol = page.getByRole("textbox", { name: "币种（留空查询全部）", exact: true });
  await symbol.fill("SOL");
  const spot = "GET /api/v1/spot/ticks";
  f.holdEvidence(spot);
  await page.getByRole("button", { name: "查询现货行情", exact: true }).click();
  await expect(symbol).toBeDisabled();
  await page.clock.runFor(15_100);
  await expect(symbol).toBeEnabled();
  await expect(symbol).toHaveValue("SOL");
  await expect(page.getByRole("tabpanel", { name: "行情诊断", exact: true })).toContainText("15 秒");
  for (const path of paths) await expect.poll(() => aborted.filter(p => p === path).length).toBe(2);
  await expect.poll(() => aborted.includes("/api/v1/spot/ticks")).toBe(true);
  await page.getByRole("tab", { name: "运行数据依据", exact: true }).click();
  await expect(search).toHaveValue("binance");
  hold = false;
  waiting.splice(0).forEach(release => release()); f.releaseEvidence(spot);
  await refresh.click();
  await expect(page.getByRole("tabpanel", { name: "运行数据依据诊断", exact: true })).not.toContainText("15 秒");
  await page.getByRole("tab", { name: "行情", exact: true }).last().click();
  await page.getByRole("button", { name: "查询现货行情", exact: true }).click();
  await expect(page.getByRole("tabpanel", { name: "行情诊断", exact: true })).toContainText("SPOT_FIXTURE_DISABLED");
  hold = true;
  await refresh.click();
  await expect.poll(() => waiting.length).toBe(5);
  await page.getByRole("tab", { name: "消息通知", exact: true }).click();
  for (const path of paths) await expect.poll(() => aborted.filter(p => p === path).length).toBe(3);
  hold = false; waiting.splice(0).forEach(release => release());
  expect(f.calls.every(r => r.key.startsWith("GET "))).toBe(true);
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});
