import { expect, test, type Page } from "@playwright/test";
import { settingsFixture } from "./fixtures/settings-workbench";
import { riskFixture } from "./fixtures/settings-risk";

const recovery = (page: Page) => page.getByRole("alert", { name: "设置操作待核对" });
const records = (page: Page) => page.evaluate(() => Object.entries(sessionStorage).filter(([key]) => key.startsWith("crossline.settings.pending.v1:")));
const check = (page: Page) => recovery(page).getByRole("button").click();
async function capture(page: Page, name: string) {
  await page.screenshot({ path: test.info().outputPath(`${name}-desktop.png`) });
  await page.setViewportSize({ width: 390, height: 844 });
  await recovery(page).scrollIntoViewIfNeeded();
  await expect(recovery(page).getByRole("button")).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: test.info().outputPath(`${name}-mobile.png`) });
  await page.setViewportSize({ width: 1280, height: 720 });
}

test("webhook and market refresh recover configuration receipts without secrets or repeat writes", async ({ page }) => {
  const f = await settingsFixture(page);
  await page.goto("/#settings");
  await page.getByLabel("投递提供方").selectOption("generic");
  const secret = page.locator('.webhook-core-grid input[type="password"]');
  await page.getByLabel("公网 HTTPS URL").fill("https://example.com/fixture-secret-target");
  await secret.fill("fixture-secret-signature");
  const path = "PATCH /api/webhook/config";
  f.hold(path);
  await page.getByRole("button", { name: "保存配置", exact: true }).click();
  await expect.poll(() => f.requests.filter((r) => r.method === "PATCH").length).toBe(1);
  const stored = await records(page);
  expect(stored).toHaveLength(1);
  expect(JSON.stringify(stored)).not.toContain("fixture-secret");
  expect(JSON.stringify(stored)).not.toContain("isolated-fixture-token");
  await page.reload();
  await expect(recovery(page)).toContainText("更新 Webhook 配置结果待核对");
  await expect(secret).toHaveValue("");
  await expect(page.getByLabel("投递提供方")).toHaveValue("bark");
  await expect(page.getByRole("button", { name: "保存配置", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "发送测试" })).toBeDisabled();
  await check(page);
  await expect(recovery(page)).toContainText("后端已受理");
  const run = f.actions.data[0];
  f.release(path);
  await expect.poll(() => run.status).toBe("succeeded");
  run.result = null;
  await check(page);
  await expect(recovery(page)).toContainText("SETTINGS_RECEIPT_MISSING");
  run.result = structuredClone(f.webhook);
  f.webhook.config.timeoutMs = 23000; f.webhook.updatedAtMs++;
  await capture(page, "webhook-recovery");
  await check(page);
  await expect(recovery(page)).toHaveCount(0);
  await expect(page.getByRole("button", { name: "保存配置", exact: true })).toBeEnabled();
  await page.locator(".webhook-advanced-settings summary").click();
  await expect(page.getByLabel("超时 ms")).toHaveValue("23000");
  await expect(secret).toHaveValue("");

  await page.getByRole("tab", { name: "行情", exact: true }).click();
  const spot = page.getByRole("checkbox", { name: "kraken 现货", exact: true });
  const marketPath = "PATCH /api/system/market-subscriptions/config";
  await expect(spot).toBeChecked();
  f.hold(marketPath); f.fail(marketPath);
  await spot.click();
  await expect.poll(() => f.requests.filter((r) => r.method === "PATCH").length).toBe(2);
  await page.reload();
  await page.getByRole("tab", { name: "行情", exact: true }).click();
  await expect(recovery(page)).toContainText("更新行情订阅结果待核对");
  await expect(spot).toBeDisabled();
  f.release(marketPath);
  await expect.poll(() => f.actions.data[0].status).toBe("failed");
  await check(page);
  await expect(recovery(page)).toHaveCount(0);
  await expect(spot).toBeEnabled();
  await expect(spot).toBeChecked();
  f.fail(marketPath, false); f.hold(marketPath);
  await spot.click();
  await expect.poll(() => f.requests.filter((r) => r.method === "PATCH").length).toBe(3);
  await page.reload();
  await page.getByRole("tab", { name: "行情", exact: true }).click();
  f.release(marketPath);
  await expect.poll(() => f.actions.data[0].status).toBe("succeeded");
  f.market.venues.find((r) => r.venue === "kraken")!.spotEnabled = true;
  f.market.updatedAtMs++;
  await check(page);
  await expect(spot).toBeEnabled();
  await expect(spot).toBeChecked();
  expect(f.requests.filter((r) => r.method !== "GET")).toHaveLength(3);
  expect(await records(page)).toEqual([]);
  expect(JSON.stringify(f.actions)).not.toContain("fixture-secret");
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});

test("risk save and kill switch reload query original outcomes and display current backend facts", async ({ page }) => {
  const f = await riskFixture(page);
  await page.goto("/#settings");
  const amount = page.getByLabel(/单笔名义上限 USD/);
  const save = page.getByRole("button", { name: "保存风控", exact: true });
  await expect(amount).toHaveValue("10");
  await amount.fill("12.75");
  f.hold();
  await save.click();
  await expect.poll(() => f.calls.length).toBe(1);
  await page.reload();
  await expect(recovery(page)).toContainText("保存风控结果待核对");
  await expect(amount).toBeDisabled();
  await expect(amount).toHaveValue("10");
  const run = f.actions.data.shift();
  await check(page);
  await expect(recovery(page)).toContainText("SETTINGS_RECEIPT_NOT_FOUND");
  f.actions.data.unshift(run);
  await check(page);
  await expect(recovery(page)).toContainText("后端已受理");
  f.release();
  await expect.poll(() => run.status).toBe("succeeded");
  const originalRequest = run.result.requestId;
  run.result.requestId = "wrong-request";
  await check(page);
  await expect(recovery(page)).toContainText("SETTINGS_RECEIPT_MISMATCH");
  await capture(page, "risk-recovery");
  run.result.requestId = originalRequest;
  f.status.risk.maxOrderNotional = 20;
  await check(page);
  await expect(recovery(page)).toHaveCount(0);
  await expect(amount).toHaveValue("20");
  await expect(save).toBeEnabled();
  expect(f.calls).toHaveLength(1);

  f.hold();
  await page.getByRole("button", { name: "切换 Kill Switch", exact: true }).click();
  await expect.poll(() => f.calls.length).toBe(2);
  const kill = f.actions.data[0];
  await page.reload();
  await expect(recovery(page)).toContainText("切换总闸结果待核对");
  await expect(save).toBeDisabled();
  f.release();
  await expect.poll(() => kill.status).toBe("succeeded");
  f.status.risk.killSwitchActive = false;
  await check(page);
  await expect(recovery(page)).toHaveCount(0);
  await expect(page.getByRole("button", { name: "切换 Kill Switch", exact: true })).toBeEnabled();
  await expect(page.locator('[data-settings-risk-scope="runtime-readonly"]')).toContainText("Kill Switch 关闭");
  expect(f.calls).toHaveLength(2);

  f.reject(true); f.hold();
  await amount.fill("25"); await save.click();
  await expect.poll(() => f.calls.length).toBe(3);
  await page.reload();
  await expect(recovery(page)).toContainText("保存风控结果待核对");
  f.release();
  await expect.poll(() => f.actions.data[0].status).toBe("failed");
  await check(page);
  await expect(recovery(page)).toHaveCount(0);
  await expect(amount).toHaveValue("20");
  await expect(save).toBeEnabled();
  expect(f.calls).toHaveLength(3);
  expect(await records(page)).toEqual([]);
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});
