import { expect, test, type Page } from "@playwright/test";
import { riskFixture } from "./fixtures/settings-risk";
import { NOW } from "./fixtures/opportunity-workbench";

const amount = (page: Page) => page.getByLabel(/单笔名义上限 USD/);
const save = (page: Page) => page.getByRole("button", { name: "保存风控", exact: true });
const editor = (page: Page) => page.locator('[data-settings-risk-scope="editable-thresholds"]');

test("risk draft and in-flight save survive navigation and recovery does not repeat writes", async ({ page }) => {
  const f = await riskFixture(page);
  await page.clock.install({ time: NOW });
  await page.goto("/#settings");
  await expect(amount(page)).toHaveValue("10");
  await amount(page).fill("12.75");
  await page.getByRole("tab", { name: "Webhook", exact: true }).click();
  await page.getByRole("tab", { name: "风控", exact: true }).click();
  await expect(amount(page)).toHaveValue("12.75");
  f.hold(); f.fail(true);
  await save(page).click();
  await expect.poll(() => f.calls.length).toBe(1);
  await page.evaluate(() => { location.hash = "review"; });
  await expect(page.locator(".settings-workspace")).toHaveCount(0);
  await page.evaluate(() => { location.hash = "settings"; });
  await expect(amount(page)).toHaveValue("12.75");
  await expect(amount(page)).toBeDisabled();
  await expect(page.getByRole("button", { name: "切换 Kill Switch" })).toBeDisabled();
  f.release();
  await expect(editor(page)).toContainText("保存结果待核对");
  await expect(amount(page)).toHaveValue("12.75");
  f.fail(false);
  await page.getByRole("button", { name: "核对上次操作", exact: true }).click();
  await expect(amount(page)).toBeEnabled();
  expect(f.calls).toHaveLength(1);
  expect(f.status.risk.maxOrderNotional).toBe(12.75);
  await expect(amount(page)).toBeEnabled();
  f.hold(); f.fail(true);
  const previousKill = f.status.risk.killSwitchActive;
  await page.getByRole("button", { name: "切换 Kill Switch" }).click();
  await expect.poll(() => f.calls.length).toBe(2);
  await page.evaluate(() => { location.hash = "review"; });
  await expect(page.locator(".settings-workspace")).toHaveCount(0);
  await page.evaluate(() => { location.hash = "settings"; });
  await expect(amount(page)).toBeDisabled();
  await expect(save(page)).toBeDisabled();
  await expect(page.getByRole("button", { name: "更新中", exact: true })).toBeDisabled();
  f.status.risk.killSwitchActive = !previousKill;
  f.release();
  const killPanel = page.locator('[data-settings-risk-scope="kill-switch-action"]');
  await expect(killPanel).toContainText("总闸结果待核对");
  await page.clock.runFor(5500);
  await expect(save(page)).toBeDisabled();
  await expect(amount(page)).toBeDisabled();
  f.fail(false);
  await page.getByRole("button", { name: "核对上次操作", exact: true }).click();
  await expect(page.getByRole("button", { name: "切换 Kill Switch" })).toBeEnabled();
  expect(f.calls).toHaveLength(2);
  expect(f.status.risk.killSwitchActive).toBe(!previousKill);
  await expect(amount(page)).toHaveValue("12.75");
  await expect(editor(page)).not.toContainText("存在未保存修改");
  await save(page).scrollIntoViewIfNeeded();
  await expect(save(page)).toBeInViewport();
  await expect(page.getByRole("button", { name: "载入最新配置", exact: true })).toBeInViewport();
  await page.screenshot({ path: test.info().outputPath("risk-save-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await save(page).scrollIntoViewIfNeeded();
  await expect(save(page)).toBeInViewport();
  await expect(page.getByRole("button", { name: "载入最新配置", exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: test.info().outputPath("risk-save-mobile.png") });
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});

test("risk saves only edited fields and refuses a conflicting backend update", async ({ page }) => {
  const f = await riskFixture(page);
  f.status.risk.autoProfitClose.minRoiBps = 0.1234;
  await page.clock.install({ time: NOW });
  await page.goto("/#settings");
  await expect(amount(page)).toHaveValue("10");
  await amount(page).fill("12.75");
  f.status.risk.autoProfitClose.minNetProfitUsd = 0.125;
  const reads = f.reads.length;
  await page.clock.runFor(5500);
  await expect.poll(() => f.reads.length).toBeGreaterThan(reads);
  await save(page).click();
  await expect(editor(page)).toContainText("风控参数已生效");
  expect(f.calls[0].body.autoProfitClose ?? null).toBeNull();
  expect(f.status.risk.autoProfitClose.minNetProfitUsd).toBe(0.125);
  await amount(page).fill("15.5");
  await expect(editor(page)).not.toContainText("风控参数已生效");
  f.status.risk.maxOrderNotional = 20;
  await page.clock.runFor(5500);
  await save(page).click();
  await expect(editor(page)).toContainText("后台同一参数已变化");
  expect(f.calls).toHaveLength(1);
  await expect(amount(page)).toHaveValue("15.5");
  await page.getByRole("button", { name: "载入最新配置", exact: true }).click();
  await expect(amount(page)).toHaveValue("20");
  await amount(page).fill("22.5");
  await save(page).click();
  await expect(editor(page)).toContainText("风控参数已生效");
  expect(f.status.risk.maxOrderNotional).toBe(22.5);
  await save(page).click();
  await expect(editor(page)).toContainText("当前配置一致");
  expect(f.calls).toHaveLength(2);
  expect(f.errors).toEqual([]); expect(f.writes).toEqual([]);
});
